[package]
name = "abi-tester-meta"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2021"
publish = false

[dependencies.abi-tester]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "0.0.1"
path = "../../../../framework/meta-lib"
default-features = false
